language: python
os: linux
dist: bionic
cache: pip
services:
  - docker
before_install:
  - docker-compose up -d
install:
  - make travis-setup
python:
  - "3.8"
script:
  - make ci

jobs:
  include:
    - stage: coverage
      python:
        - "3.8"
      script:
        - make coverage
      after_success:
        - coveralls
